### ISSUE TITLE
[Test] 회원가입 API test code

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/retry-lee#9]

**Comment by sypatrick** [comment]
_테스트 외 학습이 필요했던 부분_

#### 1. Docker desktop setting
- 정상 성공의 경우 http status 201 반환해야하는데, 500 에러가 계속 나서 확인해보니 Access Denied. `Caused by: java.sql.SQLException: Access denied for user 'patrick'@'14.63.xxx.xxx' dockerdesktop`
  - 첫번째로 들었던 생각은 로컬에서 테스트 하는데 접근 거부..? 403 에러면 Security Config 설정에서 잘못 되었나 확인했을텐데.. 혹시 몰라서 `anyRequest.permitAll()` 해도 AccessDenied
  - 두번째는 위와 같은 아이피와 함께 에러가 같이 떠서 main의 appication.yml을 읽어오나 하고 `ActiveProfiles="test"` 바꿔서 테스트해도 동일한 증상이었다. 그래서 그냥 저 아이피가 어딘가 하고 아이피 검색해보니, 데스크탑 와이파이.. 😭 
  - 해결은 윈도우 wsl2, ubuntu 에서 `sudo usermod -aG docker $USER` 해주고 reboot 하니 정상작동..
***
#### 2. DynamicPropertySource 를 사용할 때 driver-class-name 관련
- 위 문제를 해결하다가 testcontainer 의 driver-class-name은 `org.testcontainers.jdbc.ContainerDatabaseDriver` 이어야 한다고 정보를 잘못 알고 `MySQLContainer::getDriverClassName` 대신 쓰다가 계속 오류 발생
  - `Caused by: java.lang.RuntimeException: Driver org.testcontainers.jdbc.ContainerDatabaseDriver claims to not accept jdbcUrl, jdbc:mysql://localhost:14937/testdb`
  - Testcontainer 공식문서 보니 스프링부트 2.3.0 이후로는 `org.testcontainers.jdbc.ContainerDatabaseDriver` 수동으로 지정 안해줘도 된다. (참고 : https://java.testcontainers.org/modules/databases/jdbc/)
- `Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.`
  - 위 에러는 `spring.datasource.url` 이렇게 되어야 하는데, url 부분을 jdbc-url 이렇게 작성해놓아서 오류가 났었다.
***
